// function Register(){
//     return(
//         <body>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//             <span></span>
//         </body>
//     )
// }
// export default Register;